/*
 * Copyright 2019 Microchip Corporation.
 *
 * SPDX-License-Identifier: MIT
 *
 */

#include <string.h>

#include "embedded_autogenerated_data/ead_helpers.h"

#include "utils/c_template.h"

#include "http_server.h"
#include "http_structure_helpers.h"

#include "route_handlers.h"

char *get_embedded_data(http_request *req, http_response *res)
{
    ead_item_t file;

    if (!ead_find_entry(req->uri, &file))
    {
        /* Redirect to 404 because no entry found in the embedded data*/
        route_404(req, res);
        return NULL;
    }

    /* A static file found matching this URI, copy the content */
    res->content_length = file.size;
    res->content_type   = http_content_type_enum_from_string(file.content_type);

    if (EAD_CONTENT_ENCODING_GZIP == file.web_content_encoding)
    {
        res->gziped = true;
    }

    if (HTTP_CONTENT_TYPE_NULL == res->content_type)
    {
        /* The file is using unknown content type */
        res->content_type = HTTP_CONTENT_TYPE_TEXT_PLAIN;
        LWIP_DEBUGF(HTTPD_ROUTE_HANDLER_DEBUG,
                ("get_embedded_data: EAD data saved under location %s has content type '%s' which couldn't be recognized\r\n",
                file.location,
                file.content_type));
    }
    return (char *)file.data;
}


void apply_template_onto_response(
        http_response *res,
        char *data,
        c_template_variable variables[]
)
{
    strcpy(res->body, data);

    /* Add \0 just in case the data doesn't include it, the templates work
     * best with strings, not so well with raw binary data */
    res->body[res->content_length] = '\0';

    /* let the size to be auto-detect when we are finished as it might change*/
    res->content_length = -1;

    c_template_apply(res->body, variables);
}


void route_index(http_request *req, http_response *res)
{
    strcpy(res->body, "<h3>Hi</h3><img src=/resources/images/msmc_logo.png><br><img src=/resources/images/PFSoC_block_diagram.png>");
}


void route_template_index(http_request *req, http_response *res)
{
    strcat(req->uri, ".tpl"); // Request is .html but file .html.tpl
    char *data = get_embedded_data(req, res);

    if (data == NULL)
    {
        return;
    }

    c_template_variable variables[] = {
        { .key = "{{TITLE}}",        .value = "PolarFire SoC Icicle Demo" },
        { .key = "{{DYNAMIC_TEXT}}", .value = "Dynamic text" },
        { .key = NULL,               .value = NULL}
    };

    apply_template_onto_response(res, data, variables);
}


void route_static(http_request *req, http_response *res)
{
    if (0 == strcmp(req->uri,"/"))
    {
        /* if accessing root directory only, redirect to index.htm */
        strcpy(req->uri,"/index.html");
    }

    char *text_value = http_request_get_query_value(req, "text");
    if (NULL != text_value)
    {
        LWIP_DEBUGF(HTTPD_ROUTE_HANDLER_DEBUG, ("route_static: %s\r\n", text_value));
    }

    char *data = get_embedded_data(req, res);

    if (data == NULL)
    {
        return;
    }

    res->body        = data;
    res->static_body = true;
}


void route_404(http_request *req, http_response *res)
{
    res->status = HTTP_STATUS_NOT_FOUND;
    res->content_length = 0;
}


void route_internal_errorl(http_request *req, http_response *res)
{
    res->status = HTTP_STATUS_INTERNAL_SERVER_ERROR;
    res->content_length = 0;
}

