/*
 * Copyright 2019 Microchip Corporation.
 *
 * SPDX-License-Identifier: MIT
 *
 * Generated on: 24/July/2019 17:31:56
 * Auto-generated by EAD tool (v0.5.6), do not edit these files directly.
 * Send bug reports and feature requests to: anton.krug@microchip.com
 */

#ifndef EMBEDDED_AUTOGENERATED_DATA_EAD_COLLECTION_H_
#define EMBEDDED_AUTOGENERATED_DATA_EAD_COLLECTION_H_

#include "ead_structures.h"


#include "embedded_autogenerated_data/data_root_include/favicon.ico.h"
#include "embedded_autogenerated_data/data_root_include/index.html.h"
#include "embedded_autogenerated_data/data_root_include/resources/css/demo.css.h"
#include "embedded_autogenerated_data/data_root_include/resources/images/PFSoC_block_diagram.png.h"
#include "embedded_autogenerated_data/data_root_include/resources/images/msmc_logo.png.h"
#include "embedded_autogenerated_data/data_root_include/template.htm.tpl.h"
#include "embedded_autogenerated_data/data_root_include/vendors/pure-css/grids-responsive-min.css.h"
#include "embedded_autogenerated_data/data_root_include/vendors/pure-css/pure-min.css.h"


static const ead_item_t static_data_index[] = 
{
    ead_content_favicon_ico_metadata,
    ead_content_index_html_metadata,
    ead_content_resources_css_demo_css_metadata,
    ead_content_resources_images_pfsoc_block_diagram_png_metadata,
    ead_content_resources_images_msmc_logo_png_metadata,
    ead_content_template_htm_tpl_metadata,
    ead_content_vendors_pure_css_grids_responsive_min_css_metadata,
    ead_content_vendors_pure_css_pure_min_css_metadata,
 
};

#define STATIC_DATA_INDEX_SIZE (sizeof(static_data_index) / sizeof(static_data_index[0]))

#endif /* EMBEDDED_AUTOGENERATED_DATA_EAD_COLLECTION_H_ */