/*
 * Copyright 2019 Microchip Corporation.
 *
 * SPDX-License-Identifier: MIT
 *
 * Generated on: 19/July/2019 16:25:40
 * Auto-generated by EAD tool (v0.5.5), do not edit these files directly.
 * Send bug reports and feature requests to: anton.krug@microchip.com
 */

#ifndef EMBEDDED_AUTOGENERATED_DATA_EAD_CONTENT_ENCODING_H_
#define EMBEDDED_AUTOGENERATED_DATA_EAD_CONTENT_ENCODING_H_

/*
 * Only for file which are to be processed as native formats (HTML/JS/CSS),
 * but are transfered in a compressed format where content/type will not match
 * transfered format.
 *
 * Do not use on native archives such as gzip, tar.bz2 as they are compressed
 * natively, are meant to be processed as compressed/archive files and their
 * content/type is set accordingly.
 *
 * Compressed archives already have corresponding content/type set and therefore
 * content encoding should be set to NONE
 */
typedef enum 
{
    EAD_CONTENT_ENCODING_NONE,
    EAD_CONTENT_ENCODING_GZIP,
    EAD_CONTENT_ENCODING_COMPRESS,
    EAD_CONTENT_ENCODING_DEFLATE,
    EAD_CONTENT_ENCODING_IDENTITY,
    EAD_CONTENT_ENCODING_BR,
} ead_content_encoding_enum;


typedef struct 
{
    const char*                     location;
    const char*                     content_type;
    const ead_content_encoding_enum web_content_encoding;
    const unsigned char*            data;
    const unsigned int              size;
} ead_item_t;


typedef struct 
{
    ead_item_t content;
    int        current_location;
    int        error;
} ead_stream_t;


#endif /* EMBEDDED_AUTOGENERATED_DATA_EAD_CONTENT_ENCODING_H_ */