/*
 * Copyright 2019 Microchip Corporation.
 *
 * SPDX-License-Identifier: MIT
 *
 * Generated on: 19/July/2019 16:25:40
 * Auto-generated by EAD tool (v0.5.5), do not edit these files directly.
 * Send bug reports and feature requests to: anton.krug@microchip.com
 */

#ifndef EMBEDDED_AUTOGENERATED_DATA_EAD_HELPERS_H_
#define EMBEDDED_AUTOGENERATED_DATA_EAD_HELPERS_H_

#include <stdbool.h>

#include "embedded_autogenerated_data/ead_structures.h"

bool ead_find_entry(const char *location, ead_item_t *item);

ead_stream_t* ead_open(const char *filename, const char *mode);

int ead_close(ead_stream_t *stream);

int ead_fseek(ead_stream_t *stream, int offset, int origin);

int ead_error(ead_stream_t *stream);

size_t ead_read(void *ptr, size_t size, size_t nmemb, ead_stream_t *stream);


#endif /* EMBEDDED_AUTOGENERATED_DATA_EAD_HELPERS_H_ */