################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_LIST := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/application/embedded_autogenerated_data \
src/application/hart0 \
src/application/utils \
src/application/web-server \
src/modules/config/free-rtos-8.2.3-pfsoc \
src/modules/config/printf-4.0.0 \
src/modules/free-rtos-8.2.3-pfsoc \
src/modules/free-rtos-8.2.3-pfsoc/portable/GCC/RISCV \
src/modules/free-rtos-8.2.3-pfsoc/portable/MemMang \
src/modules/lwip-2.0.0-wip/api \
src/modules/lwip-2.0.0-wip/core \
src/modules/lwip-2.0.0-wip/core/ipv4 \
src/modules/lwip-2.0.0-wip/core/ipv6 \
src/modules/lwip-2.0.0-wip/netif \
src/modules/lwip-2.0.0-wip/netif/ppp \
src/modules/lwip-2.0.0-wip/netif/ppp/polarssl \
src/modules/lwip-2.0.0-wip/ping \
src/modules/lwip-2.0.0-wip-port-freertos-pfsoc/netif \
src/modules/lwip-2.0.0-wip-port-freertos-pfsoc \
src/modules/printf-4.0.0 \
src/platform/drivers/mss_gpio \
src/platform/drivers/mss_mac \
src/platform/drivers/mss_uart \
src/platform/hal \
src/platform/mpfs_hal \

